### PR TITLE
Support opentelemetry-api 1.2.x

### LINKED ISSUE #7: Support opentelemetry-api 1.2.x
Change:
```ruby
spec.add_dependency "opentelemetry-api", "~> 1.1.0"
```
to:
```ruby
spec.add_dependency "opentelemetry-api", "~> 1.1"
```

It should still work.

### PR DESCRIPTION
**Pull request by BrianHawley**
- Change requirement to "~> 1.1" to support both versions.
- Remove Gemfile.lock from the tracked files. Gem repos should exclude Gemfile.lock because if you don't, you will miss issues that come with new updates in your dependencies.
- Ignore .ruby-version and .ruby-gemset to support local development and testing.

Fixes #7

### CODE REVIEW

**Comment by BrianHawley** [comment]
@korniltsev could you review this?

**Review by korniltsev — APPROVED** [review]

**Comment by BrianHawley** [comment]
@korniltsev who merges PRs? It would be good to get this in.

**Comment by korniltsev** [comment]
I can merge but I wanted to test it by running both versions before merge

**Comment by Booocik** [comment]
@korniltsev, have you already tested it? Is there a chance to merge this PR? 👀

**Review by korniltsev — APPROVED** [review]
did not test. yolo

**Pull request merged**
